title: GitHub Pages Testing Title
author: yutampo
email: yutampo@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The description for google search and feed.xml.

# social links
twitter_username: yutampo # DO NOT include the @ character, or else the build will fail!
github_username:  yutampo # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
